name: app
type: "python:3.11"
build:
  commands:
    - pip install -r requirements.txt

web:
  commands:
    start: uvicorn main:app --host 0.0.0.0 --port $PORT
  locations:
    "/":
      passthru: true

disk: 1024
